/**
 * Agent Domain
 *
 * Types, interfaces, and schemas for the Nirex AI coding agent.
 */

export type {
  JsonSchemaProperty,
  ToolParameterSchema,
  ToolDefinition,
  ToolCall,
  ToolResult,
  ToolCategory,
  ToolRegistration,
  AgentStatus,
  AgentState,
  AgentTurn,
  ToolUseBlock,
  ToolResultBlock,
  ThinkingBlock,
  TextBlock,
  ContentBlock,
  AgentMessage,
  PermissionAction,
  PermissionRule,
  PermissionRequest,
  PermissionResponse,
  PermissionConfig,
  HookEventType,
  HookEvent,
  HookDefinition,
  SandboxProvider,
  DockerSandboxConfig,
  ProcessSandboxConfig,
  FirecrackerSandboxConfig,
  SandboxConfig,
  StreamChunkText,
  StreamChunkToolCallStart,
  StreamChunkToolCallDelta,
  StreamChunkToolCallEnd,
  StreamChunkToolResult,
  StreamChunkThinking,
  StreamChunkError,
  StreamChunkDone,
  StreamChunkMetadata,
  StreamEvent,
} from './types.js';

export {
  jsonSchemaPropertySchema,
  toolParameterSchemaSchema,
  toolDefinitionSchema,
  toolCallSchema,
  toolResultSchema,
  toolCategorySchema,
  toolRegistrationSchema,
  agentStatusSchema,
  agentTurnSchema,
  toolUseBlockSchema,
  toolResultBlockSchema,
  thinkingBlockSchema,
  textBlockSchema,
  contentBlockSchema,
  permissionActionSchema,
  permissionRuleSchema,
  permissionRequestSchema,
  permissionResponseSchema,
  permissionConfigSchema,
  hookEventTypeSchema,
  hookDefinitionSchema,
  sandboxProviderSchema,
  dockerSandboxConfigSchema,
  processSandboxConfigSchema,
  firecrackerSandboxConfigSchema,
  sandboxConfigSchema,
  streamChunkTextSchema,
  streamChunkToolCallStartSchema,
  streamChunkToolCallDeltaSchema,
  streamChunkToolCallEndSchema,
  streamChunkToolResultSchema,
  streamChunkThinkingSchema,
  streamChunkErrorSchema,
  streamChunkDoneSchema,
  streamChunkMetadataSchema,
  streamEventSchema,
} from './schemas.js';
